let
    Source = Sql.Database("10.10.0.210", "corporerm", [Query="DECLARE @datainicial date, @datafinal date#(lf)SET @datainicial = '2024-01-01'#(lf)SET @datafinal = '2026-12-31';#(lf)#(lf)WITH #(lf)op_mp AS (#(lf)#(tab)SELECT#(tab)k1.codordem,#(lf)#(tab)#(tab)#(tab)idproduto AS idprd_mp,#(lf)#(tab)#(tab)#(tab)nomefantasia AS produto_mp,#(lf)#(tab)#(tab)#(tab)SUM(k1.qtde) AS qtde_mp,#(lf)#(tab)#(tab)#(tab)SUM(t1.valorfincomsinal)*-1 AS custo_mp,#(lf)#(tab)#(tab)#(tab)'op_mp' AS Fonte#(lf)#(lf)#(tab)FROM#(tab)corporerm.dbo.kmovestoque AS k1#(lf)#(tab)#(tab)#(tab)#(tab)#(lf)#(tab)#(tab)#(tab)INNER JOIN corporerm.dbo.tprd AS p1#(lf)#(tab)#(tab)#(tab)#(tab)ON k1.idproduto = p1.idprd#(lf)#(tab)#(tab)#(tab)LEFT JOIN corporerm.dbo.trelsld AS t1#(lf)#(tab)#(tab)#(tab)#(tab)ON t1.codcoligada = k1.codcoligada AND t1.idmov = k1.idmov and k1.idproduto = t1.idprd#(lf)#(lf)#(tab)WHERE#(tab)k1.qtde > 0#(lf)#(tab)#(tab)#(tab)AND t1.datamovimento >= @datainicial#(lf)#(lf)#(tab)GROUP BY codordem, idproduto, nomefantasia#(lf)),#(lf)/*Produtos Acabados Factor*/#(lf)op_pa AS (#(lf)#(tab)SELECT#(tab)k1.codordem,#(lf)#(tab)#(tab)#(tab)CONCAT(t1.codcoligada,'|',t1.codfilial) AS key_colfilial,#(lf)#(tab)#(tab)#(tab)min(t1.datamovimento) AS data ,#(lf)#(tab)#(tab)#(tab)max(k1.idproduto) AS idprd_pa,#(lf)#(tab)#(tab)#(tab)MAX(nomefantasia) AS produto_pa,#(lf)#(tab)#(tab)#(tab)sum(k1.qtde)*-1 as qtde_pa,#(lf)#(tab)#(tab)#(tab)sum(t1.valorfincomsinal) AS custo_pa,#(lf)#(tab)#(tab)#(tab)'op_pa' AS Fonte#(lf)#(lf)#(tab)FROM#(tab)corporerm.dbo.kmovestoque AS k1#(lf)#(tab)#(tab)#(tab)#(lf)#(tab)#(tab)#(tab)INNER JOIN corporerm.dbo.tprd AS p1#(lf)#(tab)#(tab)#(tab)#(tab)ON k1.idproduto = p1.idprd#(lf)#(tab)#(tab)#(tab)LEFT JOIN corporerm.dbo.trelsld AS t1#(lf)#(tab)#(tab)#(tab)#(tab)ON t1.codcoligada = k1.codcoligada AND t1.idmov = k1.idmov and k1.idproduto = t1.idprd#(lf)#(lf)#(tab)WHERE#(tab)k1.qtde <0#(lf)#(tab)#(tab)#(tab)AND t1.datamovimento >= @datainicial#(lf)#(lf)#(tab)GROUP BY codordem,t1.codcoligada,t1.codfilial#(lf)#(lf)#(tab))#(tab)#(lf)#(lf)select year(data) as ano, month(data) as mes, key_colfilial, op_pa.codordem, idprd_pa, qtde_pa, idprd_mp, qtde_mp#(lf)from op_pa#(lf)inner join op_mp on op_pa.codordem = op_mp.codordem#(lf)"]),
    #"Run Python script" = Python.Execute("# 'dataset' holds the input data for this script#(lf)#(lf)import pandas as pd#(lf)import numpy as np#(lf)from collections import deque#(lf)from typing import Optional, Iterable, Dict, Tuple, List#(lf)import logging#(lf)import warnings#(lf)#(lf)# Configure logging#(lf)logging.basicConfig(level=logging.INFO)#(lf)logger = logging.getLogger(__name__)#(lf)#(lf)# Constants#(lf)EPSILON = 1e-12#(lf)MIN_QUANTITY_THRESHOLD = 1e-12#(lf)#(lf)#(lf)class BOMExplosionError(Exception):#(lf)    """"""Custom exception for BOM explosion errors.""""""#(lf)    pass#(lf)#(lf)#(lf)def explode_bom(#(lf)    df_bom: pd.DataFrame,#(lf)    key_colfilial: Optional[str] = None,#(lf)    roots: Optional[Iterable[int]] = None,#(lf)    max_depth: int = 50,#(lf)    max_iter: int = 20,#(lf)    tol: float = 1e-9,#(lf)    intermediate_handling: str = ""split"",#(lf)    enable_logging: bool = True#(lf)) -> pd.DataFrame:#(lf)    """"""#(lf)    Explode Bill of Materials (BOM) recursively with iterative rebalancing.#(lf)    #(lf)    This function performs a multi-phase BOM explosion:#(lf)    1. **Aggregation**: Pre-compute totals and edge ratios#(lf)    2. **Expansion**: Build full path tree using BFS with cycle detection#(lf)    3. **Rebalancing**: Iteratively adjust quantities to respect production constraints#(lf)    4. **Segmentation**: Split materials into produced vs. basic (raw materials)#(lf)    #(lf)    Args:#(lf)        df_bom: Input DataFrame with BOM structure#(lf)        key_colfilial: Filter by specific branch/facility (optional)#(lf)        roots: Specific root product IDs to explode (optional, None = all)#(lf)        max_depth: Maximum BOM tree depth to prevent infinite expansion#(lf)        max_iter: Maximum iterations for rebalancing convergence#(lf)        tol: Convergence tolerance for rebalancing algorithm#(lf)        intermediate_handling: How to handle intermediate products#(lf)            - ""split"": Split into produced (is_basic=0) and external (is_basic=1) based on #(lf)                      production vs consumption (default behavior)#(lf)            - ""full_intermediate"": Always treat intermediates as is_basic=0, skip rebalancing#(lf)                                  and always explode their BOM#(lf)        enable_logging: Enable progress logging#(lf)        #(lf)    Returns:#(lf)        DataFrame with exploded BOM#(lf)        #(lf)    Raises:#(lf)        BOMExplosionError: If BOM structure is invalid#(lf)        ValueError: If required columns are missing#(lf)    """"""#(lf)    #(lf)    # Validate parameter#(lf)    if intermediate_handling not in [""split"", ""full_intermediate""]:#(lf)        raise ValueError(f""intermediate_handling must be 'split' or 'full_intermediate', got '{intermediate_handling}'"")#(lf)    #(lf)    # ============================================================================#(lf)    # PHASE 0: Validation#(lf)    # ============================================================================#(lf)    _validate_input(df_bom)#(lf)    #(lf)    if enable_logging:#(lf)        logger.info(f""Starting BOM explosion. Input rows: {len(df_bom)}"")#(lf)        logger.info(f""Intermediate handling mode: {intermediate_handling}"")#(lf)    #(lf)    # Filter by facility if specified#(lf)    df = (#(lf)        df_bom[df_bom[""key_colfilial""] == key_colfilial].copy()#(lf)        if key_colfilial is not None#(lf)        else df_bom.copy()#(lf)    )#(lf)    #(lf)    if df.empty:#(lf)        logger.warning(""No data after filtering. Returning empty DataFrame."")#(lf)        return _empty_result_dataframe()#(lf)    #(lf)    # ============================================================================#(lf)    # PHASE 1: Aggregation - Compute totals and ratios#(lf)    # ============================================================================#(lf)    pa_totals, mp_totals, edge_ratios = _compute_aggregations(df)#(lf)    #(lf)    # Build lookup structures#(lf)    children_map = _build_children_map(edge_ratios)#(lf)    pa_total_map = _build_pa_total_map(pa_totals)#(lf)    #(lf)    # Determine roots to process#(lf)    root_keys = _determine_roots(roots, pa_total_map, key_colfilial)#(lf)    #(lf)    if enable_logging:#(lf)        logger.info(f""Processing {len(root_keys)} root products"")#(lf)    #(lf)    # ============================================================================#(lf)    # PHASE 2-4: Process each root#(lf)    # ============================================================================#(lf)    all_final_rows = []#(lf)    #(lf)    for root_key in root_keys:#(lf)        try:#(lf)            root_rows = _process_single_root(#(lf)                root_key=root_key,#(lf)                pa_total_map=pa_total_map,#(lf)                children_map=children_map,#(lf)                max_depth=max_depth,#(lf)                max_iter=max_iter,#(lf)                tol=tol,#(lf)                intermediate_handling=intermediate_handling#(lf)            )#(lf)            all_final_rows.extend(root_rows)#(lf)            #(lf)        except Exception as e:#(lf)            logger.error(f""Failed processing root {root_key}: {e}"")#(lf)            if enable_logging:#(lf)                raise BOMExplosionError(f""BOM explosion failed for root {root_key}"") from e#(lf)    #(lf)    # ============================================================================#(lf)    # PHASE 5: Finalize output#(lf)    # ============================================================================#(lf)    if not all_final_rows:#(lf)        logger.warning(""No results generated"")#(lf)        return _empty_result_dataframe()#(lf)    #(lf)    df_final = _finalize_dataframe(all_final_rows)#(lf)    #(lf)    # For full_intermediate mode, aggregate duplicate raw materials#(lf)    if intermediate_handling == ""full_intermediate"":#(lf)        df_final = _aggregate_raw_materials(df_final)#(lf)    #(lf)    if enable_logging:#(lf)        logger.info(f""BOM explosion complete. Output rows: {len(df_final)}"")#(lf)        logger.info(f""Basic materials: {(df_final['is_basic']==1).sum()}, ""#(lf)                   f""Produced components: {(df_final['is_basic']==0).sum()}"")#(lf)    #(lf)    return df_final#(lf)#(lf)#(lf)# ==============================================================================#(lf)# HELPER FUNCTIONS#(lf)# ==============================================================================#(lf)#(lf)def _validate_input(df_bom: pd.DataFrame) -> None:#(lf)    """"""Validate input DataFrame has required columns.""""""#(lf)    required = {#(lf)        ""ano"", ""mes"", ""key_colfilial"",#(lf)        ""codordem"", ""idprd_pa"", ""qtde_pa"",#(lf)        ""idprd_mp"", ""qtde_mp""#(lf)    }#(lf)    missing = required - set(df_bom.columns)#(lf)    if missing:#(lf)        raise ValueError(f""Missing required columns: {missing}"")#(lf)    #(lf)    if df_bom.empty:#(lf)        raise ValueError(""Input DataFrame is empty"")#(lf)#(lf)#(lf)def _compute_aggregations(#(lf)    df: pd.DataFrame#(lf)) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:#(lf)    """"""#(lf)    Compute aggregated totals and edge ratios.#(lf)    #(lf)    Returns:#(lf)        (pa_totals, mp_totals, edge_ratios)#(lf)    """"""#(lf)    # Parent product totals (sum across all orders)#(lf)    pa_totals = (#(lf)        df[[""ano"", ""mes"", ""key_colfilial"", ""codordem"", ""idprd_pa"", ""qtde_pa""]]#(lf)        .drop_duplicates([""ano"", ""mes"", ""key_colfilial"", ""codordem"", ""idprd_pa""])#(lf)        .groupby([""ano"", ""mes"", ""key_colfilial"", ""idprd_pa""], as_index=False)#(lf)        .agg(qtde_pa_total=(""qtde_pa"", ""sum""))#(lf)    )#(lf)    #(lf)    # Material totals per parent#(lf)    mp_totals = (#(lf)        df.groupby(#(lf)            [""ano"", ""mes"", ""key_colfilial"", ""codordem"", ""idprd_pa"", ""idprd_mp""],#(lf)            as_index=False#(lf)        )#(lf)        .agg(qtde_mp_order=(""qtde_mp"", ""sum""))#(lf)        .groupby(#(lf)            [""ano"", ""mes"", ""key_colfilial"", ""idprd_pa"", ""idprd_mp""],#(lf)            as_index=False#(lf)        )#(lf)        .agg(qtde_mp_total=(""qtde_mp_order"", ""sum""))#(lf)    )#(lf)    #(lf)    # Compute edge ratios (material qty / parent qty)#(lf)    edge_ratios = mp_totals.merge(#(lf)        pa_totals,#(lf)        on=[""ano"", ""mes"", ""key_colfilial"", ""idprd_pa""],#(lf)        how=""left""#(lf)    )#(lf)    #(lf)    # Vectorized ratio computation#(lf)    edge_ratios[""ratio""] = np.where(#(lf)        edge_ratios[""qtde_pa_total""] > 0,#(lf)        edge_ratios[""qtde_mp_total""] / edge_ratios[""qtde_pa_total""],#(lf)        0.0#(lf)    )#(lf)    #(lf)    return pa_totals, mp_totals, edge_ratios#(lf)#(lf)#(lf)def _build_children_map(#(lf)    edge_ratios: pd.DataFrame#(lf)) -> Dict[Tuple[int, int, str, int], List[Tuple[int, float]]]:#(lf)    """"""Build mapping of parent -> [(child, ratio), ...]""""""#(lf)    children_map = {}#(lf)    #(lf)    # Use itertuples for better performance than iterrows#(lf)    for row in edge_ratios.sort_values([""idprd_pa"", ""idprd_mp""]).itertuples():#(lf)        key = (row.ano, row.mes, row.key_colfilial, row.idprd_pa)#(lf)        children_map.setdefault(key, []).append((row.idprd_mp, row.ratio))#(lf)    #(lf)    return children_map#(lf)#(lf)#(lf)def _build_pa_total_map(#(lf)    pa_totals: pd.DataFrame#(lf)) -> Dict[Tuple[int, int, str, int], float]:#(lf)    """"""Build mapping of (ano, mes, facility, product) -> total quantity""""""#(lf)    return {#(lf)        (row.ano, row.mes, row.key_colfilial, row.idprd_pa): row.qtde_pa_total#(lf)        for row in pa_totals.itertuples()#(lf)    }#(lf)#(lf)#(lf)def _determine_roots(#(lf)    roots: Optional[Iterable[int]],#(lf)    pa_total_map: Dict[Tuple[int, int, str, int], float],#(lf)    key_colfilial: Optional[str]#(lf)) -> List[Tuple[int, int, str, int]]:#(lf)    """"""Determine which root products to process.""""""#(lf)    if roots is None:#(lf)        return sorted(pa_total_map.keys())#(lf)    #(lf)    root_set = set(int(r) for r in roots)#(lf)    root_keys = [#(lf)        key for key in pa_total_map.keys()#(lf)        if key[3] in root_set and (key_colfilial is None or key[2] == key_colfilial)#(lf)    ]#(lf)    #(lf)    if not root_keys:#(lf)        logger.warning(f""No matching roots found for specified IDs: {roots}"")#(lf)    #(lf)    return sorted(root_keys)#(lf)#(lf)#(lf)def _process_single_root(#(lf)    root_key: Tuple[int, int, str, int],#(lf)    pa_total_map: Dict[Tuple[int, int, str, int], float],#(lf)    children_map: Dict[Tuple[int, int, str, int], List[Tuple[int, float]]],#(lf)    max_depth: int,#(lf)    max_iter: int,#(lf)    tol: float,#(lf)    intermediate_handling: str#(lf)) -> List[Dict]:#(lf)    """"""Process a single root product through all explosion phases.""""""#(lf)    ano, mes, key_col, pa_root = root_key#(lf)    root_qty = pa_total_map[root_key]#(lf)    #(lf)    # Phase 2: Initial BFS expansion#(lf)    df_edges, loop_detected = _bfs_expansion(#(lf)        root_node=pa_root,#(lf)        root_qty=root_qty,#(lf)        ano=ano,#(lf)        mes=mes,#(lf)        key_col=key_col,#(lf)        children_map=children_map,#(lf)        max_depth=max_depth#(lf)    )#(lf)    #(lf)    if df_edges.empty:#(lf)        return []#(lf)    #(lf)    # Phase 3: Iterative rebalancing (only for split mode)#(lf)    if intermediate_handling == ""split"":#(lf)        df_edges = _iterative_rebalancing(#(lf)            df_edges=df_edges,#(lf)            pa_total_map=pa_total_map,#(lf)            ano=ano,#(lf)            mes=mes,#(lf)            key_col=key_col,#(lf)            root_node=pa_root,#(lf)            root_qty=root_qty,#(lf)            max_iter=max_iter,#(lf)            tol=tol#(lf)        )#(lf)    else:  # full_intermediate#(lf)        # No rebalancing - all quantities stay as expanded#(lf)        # Mark as produced (will be filtered in segmentation)#(lf)        df_edges[""produced_part""] = df_edges[""qty_edge""]#(lf)        df_edges[""basic_part""] = 0.0#(lf)    #(lf)    # Phase 4: Segmentation into produced/basic#(lf)    final_rows = _segment_edges(#(lf)        df_edges=df_edges,#(lf)        ano=ano,#(lf)        mes=mes,#(lf)        key_col=key_col,#(lf)        pa_root=pa_root,#(lf)        root_qty=root_qty,#(lf)        intermediate_handling=intermediate_handling,#(lf)        children_map=children_map#(lf)    )#(lf)    #(lf)    return final_rows#(lf)#(lf)#(lf)def _bfs_expansion(#(lf)    root_node: int,#(lf)    root_qty: float,#(lf)    ano: int,#(lf)    mes: int,#(lf)    key_col: str,#(lf)    children_map: Dict[Tuple[int, int, str, int], List[Tuple[int, float]]],#(lf)    max_depth: int#(lf)) -> Tuple[pd.DataFrame, bool]:#(lf)    """"""#(lf)    Perform BFS expansion of BOM tree with cycle detection.#(lf)    #(lf)    Returns:#(lf)        (df_edges, loop_detected)#(lf)    """"""#(lf)    q = deque()#(lf)    q.append((root_node, root_qty, (root_node,), 0, False))#(lf)    #(lf)    rows = []#(lf)    loop_detected = False#(lf)    #(lf)    while q:#(lf)        node, qty, path, nivel, has_loop = q.popleft()#(lf)        #(lf)        # Check max depth#(lf)        if nivel >= max_depth:#(lf)            logger.warning(f""Max depth {max_depth} reached for path {path}"")#(lf)            rows.append({#(lf)                ""path_str"": _format_path(path),#(lf)                ""idprd_mp"": node,#(lf)                ""ratio"": None,#(lf)                ""nivel"": nivel,#(lf)                ""qtde_pa"": root_qty,#(lf)                ""qtde_mp"": qty,#(lf)                ""has_loop"": has_loop#(lf)            })#(lf)            continue#(lf)        #(lf)        key_node = (ano, mes, key_col, node)#(lf)        children = children_map.get(key_node)#(lf)        #(lf)        # Leaf node - no children#(lf)        if not children:#(lf)            rows.append({#(lf)                ""path_str"": _format_path(path),#(lf)                ""idprd_mp"": node,#(lf)                ""ratio"": None,#(lf)                ""nivel"": nivel,#(lf)                ""qtde_pa"": root_qty,#(lf)                ""qtde_mp"": qty,#(lf)                ""has_loop"": has_loop#(lf)            })#(lf)            continue#(lf)        #(lf)        # Process each child#(lf)        for child, ratio in children:#(lf)            next_qty = qty * ratio#(lf)            path_next = path + (child,)#(lf)            #(lf)            # Cycle detection#(lf)            child_has_loop = has_loop or (child in path)#(lf)            if child_has_loop:#(lf)                loop_detected = True#(lf)            #(lf)            rows.append({#(lf)                ""path_str"": _format_path(path_next),#(lf)                ""idprd_mp"": child,#(lf)                ""ratio"": ratio,#(lf)                ""nivel"": nivel + 1,#(lf)                ""qtde_pa"": root_qty,#(lf)                ""qtde_mp"": next_qty,#(lf)                ""has_loop"": child_has_loop#(lf)            })#(lf)            #(lf)            # Continue expansion only if no cycle and child has children#(lf)            child_has_children = (ano, mes, key_col, child) in children_map#(lf)            if child_has_children and not child_has_loop:#(lf)                q.append((child, next_qty, path_next, nivel + 1, child_has_loop))#(lf)    #(lf)    if not rows:#(lf)        return pd.DataFrame(), loop_detected#(lf)    #(lf)    df_edges = pd.DataFrame(rows).sort_values(""nivel"").reset_index(drop=True)#(lf)    df_edges[""parent_path""] = df_edges[""path_str""].apply(_get_parent_path)#(lf)    df_edges[""qty_edge""] = df_edges[""qtde_mp""].astype(float)#(lf)    #(lf)    return df_edges, loop_detected#(lf)#(lf)#(lf)def _iterative_rebalancing(#(lf)    df_edges: pd.DataFrame,#(lf)    pa_total_map: Dict[Tuple[int, int, str, int], float],#(lf)    ano: int,#(lf)    mes: int,#(lf)    key_col: str,#(lf)    root_node: int,#(lf)    root_qty: float,#(lf)    max_iter: int,#(lf)    tol: float#(lf)) -> pd.DataFrame:#(lf)    """"""#(lf)    Iteratively rebalance edge quantities to respect production constraints.#(lf)    #(lf)    This ensures that if a material is both consumed and produced,#(lf)    the consumed quantity doesn't exceed the produced quantity.#(lf)    """"""#(lf)    # Build production capacity map#(lf)    produced_map = {#(lf)        pa_id: qty#(lf)        for (a, m, k, pa_id), qty in pa_total_map.items()#(lf)        if a == ano and m == mes and k == key_col#(lf)    }#(lf)    #(lf)    prev_ratio_map = {}#(lf)    converged = False#(lf)    #(lf)    for iteration in range(max_iter):#(lf)        # Compute total consumed per material#(lf)        total_consumed = (#(lf)            df_edges.groupby(""idprd_mp"", as_index=False)#(lf)            .agg(total_consumed=(""qty_edge"", ""sum""))#(lf)        )#(lf)        #(lf)        # Vectorized produced_ratio computation#(lf)        total_consumed[""produced_total""] = total_consumed[""idprd_mp""].map(#(lf)            produced_map#(lf)        ).fillna(0.0)#(lf)        #(lf)        total_consumed[""produced_ratio""] = np.minimum(#(lf)            1.0,#(lf)            np.where(#(lf)                total_consumed[""total_consumed""] > 0,#(lf)                total_consumed[""produced_total""] / total_consumed[""total_consumed""],#(lf)                0.0#(lf)            )#(lf)        )#(lf)        #(lf)        ratio_map = dict(zip(#(lf)            total_consumed[""idprd_mp""],#(lf)            total_consumed[""produced_ratio""]#(lf)        ))#(lf)        #(lf)        # Check convergence#(lf)        if iteration > 0:#(lf)            max_change = max(#(lf)                abs(ratio_map.get(k, 0) - prev_ratio_map.get(k, 0))#(lf)                for k in set(ratio_map.keys()) | set(prev_ratio_map.keys())#(lf)            )#(lf)            #(lf)            if max_change < tol:#(lf)                converged = True#(lf)                logger.debug(f""Converged in {iteration} iterations"")#(lf)                break#(lf)        #(lf)        prev_ratio_map = ratio_map.copy()#(lf)        #(lf)        # Compute produced_part using vectorized operations#(lf)        df_edges[""produced_part""] = (#(lf)            df_edges[""qty_edge""] *#(lf)            df_edges[""idprd_mp""].map(ratio_map).fillna(0.0)#(lf)        )#(lf)        #(lf)        # Build produced_part lookup#(lf)        produced_part_map = dict(zip(#(lf)            df_edges[""path_str""],#(lf)            df_edges[""produced_part""]#(lf)        ))#(lf)        produced_part_map[f""|{root_node}|""] = root_qty  # Add root#(lf)        #(lf)        # Recompute qty_edge by propagating parent produced_part#(lf)        new_qty = []#(lf)        for row in df_edges.itertuples():#(lf)            parent_path = row.parent_path#(lf)            ratio = row.ratio if pd.notna(row.ratio) else 1.0#(lf)            #(lf)            parent_prod = produced_part_map.get(parent_path, 0.0)#(lf)            new_qty.append(parent_prod * ratio)#(lf)        #(lf)        df_edges[""qty_edge""] = new_qty#(lf)    #(lf)    # Warn if not converged#(lf)    if not converged:#(lf)        max_change = max(#(lf)            abs(ratio_map.get(k, 0) - prev_ratio_map.get(k, 0))#(lf)            for k in set(ratio_map.keys()) | set(prev_ratio_map.keys())#(lf)        )#(lf)        warnings.warn(#(lf)            f""Rebalancing did not converge after {max_iter} iterations. ""#(lf)            f""Max change: {max_change:.2e} > tolerance: {tol:.2e}""#(lf)        )#(lf)    #(lf)    # Compute final produced/basic parts#(lf)    df_edges[""produced_part""] = (#(lf)        df_edges[""qty_edge""] *#(lf)        df_edges[""idprd_mp""].map(prev_ratio_map).fillna(0.0)#(lf)    )#(lf)    df_edges[""basic_part""] = df_edges[""qty_edge""] - df_edges[""produced_part""]#(lf)    #(lf)    return df_edges#(lf)#(lf)#(lf)def _segment_edges(#(lf)    df_edges: pd.DataFrame,#(lf)    ano: int,#(lf)    mes: int,#(lf)    key_col: str,#(lf)    pa_root: int,#(lf)    root_qty: float,#(lf)    intermediate_handling: str,#(lf)    children_map: Dict[Tuple[int, int, str, int], List[Tuple[int, float]]]#(lf)) -> List[Dict]:#(lf)    """"""#(lf)    Split edges into produced components and basic materials.#(lf)    #(lf)    In ""split"" mode:#(lf)        - Each edge may generate two rows based on produced/basic split#(lf)    #(lf)    In ""full_intermediate"" mode:#(lf)        - Only create rows for materials that DON'T have a BOM (true raw materials)#(lf)        - Skip any material that has children (intermediates are fully exploded)#(lf)    """"""#(lf)    final_rows = []#(lf)    #(lf)    for row in df_edges.itertuples():#(lf)        # Check if this material is an intermediate (has a BOM)#(lf)        key_node = (ano, mes, key_col, row.idprd_mp)#(lf)        is_intermediate = key_node in children_map#(lf)        #(lf)        if intermediate_handling == ""full_intermediate"":#(lf)            # Only output if this is a TRUE basic material (no BOM)#(lf)            if not is_intermediate:#(lf)                # This is a raw material - output as basic#(lf)                if row.produced_part > MIN_QUANTITY_THRESHOLD:#(lf)                    basic_ratio = row.produced_part / root_qty if root_qty > 0 else 0.0#(lf)                    final_rows.append({#(lf)                        ""ano"": ano,#(lf)                        ""mes"": mes,#(lf)                        ""key_colfilial"": key_col,#(lf)                        ""idprd_pa"": pa_root,#(lf)                        ""qtde_pa"": root_qty,#(lf)                        ""idprd_mp"": row.idprd_mp,#(lf)                        ""qtde_mp"": row.produced_part,#(lf)                        ""nivel"": row.nivel,#(lf)                        ""has_loop"": row.has_loop,#(lf)                        ""path_str"": row.path_str,#(lf)                        ""ratio"": row.ratio,#(lf)                        ""is_basic"": 1,#(lf)                        ""basic_ratio"": basic_ratio#(lf)                    })#(lf)            # If it's an intermediate, skip it - it's already been exploded in BFS#(lf)            #(lf)        else:  # ""split"" mode - original behavior#(lf)            # Produced component row#(lf)            if row.produced_part > MIN_QUANTITY_THRESHOLD:#(lf)                final_rows.append({#(lf)                    ""ano"": ano,#(lf)                    ""mes"": mes,#(lf)                    ""key_colfilial"": key_col,#(lf)                    ""idprd_pa"": pa_root,#(lf)                    ""qtde_pa"": root_qty,#(lf)                    ""idprd_mp"": row.idprd_mp,#(lf)                    ""qtde_mp"": row.produced_part,#(lf)                    ""nivel"": row.nivel,#(lf)                    ""has_loop"": row.has_loop,#(lf)                    ""path_str"": row.path_str,#(lf)                    ""ratio"": row.ratio,#(lf)                    ""is_basic"": 0,#(lf)                    ""basic_ratio"": 0.0#(lf)                })#(lf)            #(lf)            # Basic material row#(lf)            if row.basic_part > MIN_QUANTITY_THRESHOLD:#(lf)                basic_ratio = row.basic_part / root_qty if root_qty > 0 else 0.0#(lf)                final_rows.append({#(lf)                    ""ano"": ano,#(lf)                    ""mes"": mes,#(lf)                    ""key_colfilial"": key_col,#(lf)                    ""idprd_pa"": pa_root,#(lf)                    ""qtde_pa"": root_qty,#(lf)                    ""idprd_mp"": row.idprd_mp,#(lf)                    ""qtde_mp"": row.basic_part,#(lf)                    ""nivel"": row.nivel,#(lf)                    ""has_loop"": row.has_loop,#(lf)                    ""path_str"": row.path_str,#(lf)                    ""ratio"": row.ratio,#(lf)                    ""is_basic"": 1,#(lf)                    ""basic_ratio"": basic_ratio#(lf)                })#(lf)    #(lf)    return final_rows#(lf)#(lf)#(lf)def _finalize_dataframe(rows: List[Dict]) -> pd.DataFrame:#(lf)    """"""Convert row list to final DataFrame with proper types.""""""#(lf)    df = pd.DataFrame(rows)#(lf)    #(lf)    # Type conversions#(lf)    df[""qtde_mp""] = pd.to_numeric(df[""qtde_mp""], errors=""coerce"").fillna(0.0)#(lf)    df[""qtde_pa""] = pd.to_numeric(df[""qtde_pa""], errors=""coerce"").fillna(0.0)#(lf)    df[""nivel""] = df[""nivel""].astype(int)#(lf)    df[""has_loop""] = df[""has_loop""].astype(bool)#(lf)    df[""is_basic""] = df[""is_basic""].astype(int)#(lf)    df[""basic_ratio""] = pd.to_numeric(#(lf)        df.get(""basic_ratio"", 0.0),#(lf)        errors=""coerce""#(lf)    ).fillna(0.0)#(lf)    #(lf)    # Sort for consistency#(lf)    df = df.sort_values(#(lf)        [""ano"", ""mes"", ""key_colfilial"", ""idprd_pa"", ""nivel"", ""idprd_mp""]#(lf)    ).reset_index(drop=True)#(lf)    #(lf)    return df#(lf)#(lf)#(lf)def _empty_result_dataframe() -> pd.DataFrame:#(lf)    """"""Return empty DataFrame with correct schema.""""""#(lf)    return pd.DataFrame(columns=[#(lf)        ""ano"", ""mes"", ""key_colfilial"",#(lf)        ""idprd_pa"", ""qtde_pa"",#(lf)        ""idprd_mp"", ""qtde_mp"",#(lf)        ""nivel"", ""has_loop"", ""path_str"", ""ratio"",#(lf)        ""is_basic"", ""basic_ratio""#(lf)    ])#(lf)#(lf)#(lf)def _format_path(path: Tuple[int, ...]) -> str:#(lf)    """"""Format path tuple as string: (1,2,3) -> '|1|2|3|'""""""#(lf)    return ""|"" + ""|"".join(map(str, path)) + ""|""#(lf)#(lf)#(lf)def _get_parent_path(path_str: str) -> Optional[str]:#(lf)    """"""Extract parent path from path string.""""""#(lf)    s = path_str.rstrip(""|"")#(lf)    idx = s.rfind(""|"")#(lf)    if idx == -1:#(lf)        return None#(lf)    return s[:idx + 1]#(lf)#(lf)#(lf)def _aggregate_raw_materials(df: pd.DataFrame) -> pd.DataFrame:#(lf)    """"""#(lf)    Aggregate raw materials in full_intermediate mode.#(lf)    #(lf)    Since the same raw material can appear through multiple paths#(lf)    (e.g., 45299 through |6913|45299| and |6913|279|45299|),#(lf)    we need to sum them up to get the total requirement.#(lf)    #(lf)    We keep the shortest path (lowest nivel) for each material.#(lf)    """"""#(lf)    if df.empty:#(lf)        return df#(lf)    #(lf)    # Group by root and material#(lf)    aggregated = (#(lf)        df.groupby(['ano', 'mes', 'key_colfilial', 'idprd_pa', 'qtde_pa', 'idprd_mp', 'is_basic'])#(lf)        .agg({#(lf)            'qtde_mp': 'sum',  # Sum quantities from all paths#(lf)            'nivel': 'min',    # Keep shortest path level#(lf)            'has_loop': 'any',#(lf)            'path_str': 'first',  # Keep first path (could be min nivel)#(lf)            'ratio': 'first',#(lf)            'basic_ratio': 'sum'  # Sum basic ratios#(lf)        })#(lf)        .reset_index()#(lf)    )#(lf)    #(lf)    # Recalculate basic_ratio based on aggregated quantities#(lf)    aggregated['basic_ratio'] = np.where(#(lf)        aggregated['qtde_pa'] > 0,#(lf)        aggregated['qtde_mp'] / aggregated['qtde_pa'],#(lf)        0.0#(lf)    )#(lf)    #(lf)    # Sort for consistency#(lf)    aggregated = aggregated.sort_values(#(lf)        ['ano', 'mes', 'key_colfilial', 'idprd_pa', 'nivel', 'idprd_mp']#(lf)    ).reset_index(drop=True)#(lf)    #(lf)    return aggregated#(lf)#(lf)result = explode_bom (df_bom=dataset,max_depth=10,max_iter=30, intermediate_handling=""full_intermediate"")#(lf)",[dataset=Source]),
    result = #"Run Python script"{[Name="result"]}[Value],
#"Changed Type" =
    Table.TransformColumnTypes(
        result,
        {
            {"ano", Int64.Type},
            {"mes", Int64.Type},
            {"key_colfilial", type text},
            {"idprd_pa", Int64.Type},
            {"qtde_pa", Int64.Type},
            {"idprd_mp", Int64.Type},
            {"qtde_mp", Int64.Type},
            {"nivel", Int64.Type},
            {"has_loop", type logical},
            {"path_str", type text},
            {"ratio", type number},
            {"is_basic", Int64.Type},
            {"basic_ratio", type number}
        },
        "en-US"
    ),
    #"Run Python script1" = Python.Execute("import pandas as pd#(lf)import numpy as np#(lf)#(lf)# ====================================================#(lf)# INPUT TABLES#(lf)# ====================================================#(lf)#(lf)df_in = df.copy()#(lf)df_out = df_explodido.copy()#(lf)#(lf)# ====================================================#(lf)# OPTIONAL FILTERS#(lf)# Leave as None to disable#(lf)# ====================================================#(lf)#(lf)key_colfilial = None#(lf)ano = None#(lf)mes = None#(lf)#(lf)if key_colfilial is not None:#(lf)    df_in = df_in[df_in[""key_colfilial""] == key_colfilial]#(lf)    df_out = df_out[df_out[""key_colfilial""] == key_colfilial]#(lf)#(lf)if ano is not None:#(lf)    df_in = df_in[df_in[""ano""] == ano]#(lf)    df_out = df_out[df_out[""ano""] == ano]#(lf)#(lf)if mes is not None:#(lf)    df_in = df_in[df_in[""mes""] == mes]#(lf)    df_out = df_out[df_out[""mes""] == mes]#(lf)#(lf)# ====================================================#(lf)# TOTAL PRODUCED#(lf)# ====================================================#(lf)#(lf)produced = (#(lf)    df_in[#(lf)        [#(lf)            ""ano"",#(lf)            ""mes"",#(lf)            ""key_colfilial"",#(lf)            ""idprd_pa"",#(lf)            ""codordem"",#(lf)            ""qtde_pa""#(lf)        ]#(lf)    ]#(lf)    .drop_duplicates(#(lf)        [#(lf)            ""ano"",#(lf)            ""mes"",#(lf)            ""key_colfilial"",#(lf)            ""codordem"",#(lf)            ""idprd_pa""#(lf)        ]#(lf)    )#(lf)    .groupby(#(lf)        [#(lf)            ""ano"",#(lf)            ""mes"",#(lf)            ""key_colfilial"",#(lf)            ""idprd_pa""#(lf)        ],#(lf)        as_index=False#(lf)    )#(lf)    .agg(#(lf)        produced_total=(""qtde_pa"", ""sum"")#(lf)    )#(lf))#(lf)#(lf)# ====================================================#(lf)# INTERMEDIATE CONSUMPTION#(lf)# ====================================================#(lf)#(lf)consumed_inter_raw = (#(lf)    df_out[#(lf)        (df_out[""is_basic""] == 0) &#(lf)        (df_out[""nivel""] == 1)#(lf)    ]#(lf)    .groupby(#(lf)        [#(lf)            ""ano"",#(lf)            ""mes"",#(lf)            ""key_colfilial"",#(lf)            ""idprd_mp""#(lf)        ],#(lf)        as_index=False#(lf)    )#(lf)    .agg(#(lf)        consumed_intermediate_raw=(""qtde_mp"", ""sum"")#(lf)    )#(lf)    .rename(#(lf)        columns={#(lf)            ""idprd_mp"": ""idprd_pa""#(lf)        }#(lf)    )#(lf))#(lf)#(lf)# ====================================================#(lf)# MERGE#(lf)# ====================================================#(lf)#(lf)summary = produced.merge(#(lf)    consumed_inter_raw,#(lf)    on=[#(lf)        ""ano"",#(lf)        ""mes"",#(lf)        ""key_colfilial"",#(lf)        ""idprd_pa""#(lf)    ],#(lf)    how=""left""#(lf))#(lf)#(lf)summary[""consumed_intermediate_raw""] = (#(lf)    summary[""consumed_intermediate_raw""]#(lf)    .fillna(0)#(lf))#(lf)#(lf)# ====================================================#(lf)# LIMITED INTERMEDIATE CONSUMPTION#(lf)# ====================================================#(lf)#(lf)summary[""consumed_intermediate""] = np.minimum(#(lf)    summary[""produced_total""],#(lf)    summary[""consumed_intermediate_raw""]#(lf))#(lf)#(lf)# ====================================================#(lf)# BASIC CONSUMPTION#(lf)# ====================================================#(lf)#(lf)summary[""consumed_basic""] = (#(lf)    summary[""consumed_intermediate_raw""]#(lf)    - summary[""consumed_intermediate""]#(lf))#(lf)#(lf)# ====================================================#(lf)# NET PRODUCTION#(lf)# ====================================================#(lf)#(lf)summary[""net_production""] = (#(lf)    summary[""produced_total""]#(lf)    - summary[""consumed_intermediate""]#(lf))#(lf)#(lf)# ====================================================#(lf)# OUTPUT#(lf)# ====================================================#(lf)#(lf)dataset = summary[#(lf)    [#(lf)        ""ano"",#(lf)        ""mes"",#(lf)        ""key_colfilial"",#(lf)        ""idprd_pa"",#(lf)        ""produced_total"",#(lf)        ""consumed_intermediate"",#(lf)        ""consumed_basic"",#(lf)        ""net_production""#(lf)    ]#(lf)]",[dataset=#"Changed Type"]),
    #"Added Custom" = Table.AddColumn(#"Run Python script1", "Data", each Date.EndOfMonth( #date ([ano], [mes], 1 ) )),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Data", type date}})
in
    #"Changed Type1"